# Generated by Django 5.1.7 on 2025-03-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coupon_alter_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
