# Generated by Django 5.1.7 on 2025-03-30 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_saves_order_saved_alter_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 13, 15, 49, 820808, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
