# Generated by Django 5.1.7 on 2025-04-05 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 15, 54, 6, 415829, tzinfo=datetime.timezone.utc)),
        ),
    ]
