# Generated by Django 5.1.7 on 2025-04-06 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 6, 54, 31, 63706, tzinfo=datetime.timezone.utc)),
        ),
    ]
