# Generated by Django 5.1.7 on 2025-05-03 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 14, 6, 51, 610156, tzinfo=datetime.timezone.utc)),
        ),
    ]
